use email_address::EmailAddress;
use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;
use surrealdb::sql::Datetime;

use crate::models::ids::UserId;

#[derive(Debug, thiserror::Error)]
pub enum UsernameError {
    #[error("Username length must be more than 3 characters, but was {0}")]
    TooShort(usize),
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Username(pub String);

impl Username {
    pub fn new(value: String) -> Result<Self, UsernameError> {
        if value.len() < 3 {
            Err(UsernameError::TooShort(value.len()))
        } else {
            Ok(Self(value))
        }
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum UserRole {
    User,
    Admin,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct User {
    pub id: Option<UserId>,
    pub created_at: Datetime,
    pub updated_at: Datetime,
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub username: String, // should remove
    pub is_deleted: bool,
    pub role: UserRole,
}

impl User {
    pub fn from_insert(input: InsertUser) -> Self {
        Self {
            id: None, // generated by surrealdb
            created_at: Datetime::default(),
            updated_at: Datetime::default(),
            email: input.email.to_string(),
            first_name: input.first_name,
            last_name: input.last_name,
            username: input.username.as_str().to_string(),
            is_deleted: false,
            role: UserRole::User,
        }
    }
    pub fn can_admin(&self) -> bool {
        matches!(self.role, UserRole::Admin)
    }

    pub fn can_edit_user(&self, target: &UserId) -> bool {
        self.can_admin() || self.id == Some(target.clone())
    }

    pub fn can_list_users(&self) -> bool {
        self.can_admin()
    }

    pub fn can_delete_user(&self, target: &UserId) -> bool {
        self.can_admin() || self.id == Some(target.clone())
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct InsertUser {
    pub first_name: String,
    pub last_name: String,
    pub username: Username,
    pub email: EmailAddress,
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UserPatch {
    pub username: Option<Username>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub is_deleted: Option<bool>,
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AdminUserPatch {
    pub username: Option<Username>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub is_deleted: Option<bool>,
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SelfUserPatch {
    pub username: Option<Username>,
}

impl From<UserPatch> for AdminUserPatch {
    fn from(patch: UserPatch) -> Self {
        AdminUserPatch {
            username: patch.username,
            first_name: patch.first_name,
            last_name: patch.last_name,
            is_deleted: patch.is_deleted,
        }
    }
}

impl From<UserPatch> for SelfUserPatch {
    fn from(patch: UserPatch) -> Self {
        SelfUserPatch {
            username: patch.username,
        }
    }
}
